### ISSUE TITLE
Comment support for config paths.

### ISSUE THREAD

**Issue by portlek** [HSGamer/HSCore#39]
- Make config-path modules decorator pattern first.
- Add CommentedPath decorator.
```java
Paths.commented(
  Paths.booleanPath("test", true),
  "Up comment",
  "Side comment",
  "Down comment"
);
```
```yml
# Up comment
test: true # Side comment
# Down comment
```

If you have never use the decorator pattern, you can check that
https://github.com/yegor256/cactoos#textstrings

**Comment by HSGamer** [comment]
The pattern is new to me. I've never used that.
And I don't think of a way to do that.

For the CommentedPath, since the ConfigPath is shared for all file types, adding it directly to the config-path module may not be a good idea. If your example is for YAML, there may be a separated module for that

**Comment by portlek** [comment]
I will do it on my other repository. It can be a little bit weird for this project. We can discuss the result after I make it.
